#!/usr/bin/env python3
"""Script version of training/Train.ipynb (full fine-tuning of Qwen3-VL-4B-Instruct).

Training code, hyper-parameters and the augmentation pipeline are copied unchanged from the
notebook (including the albumentations 1.x argument names). Additions only:
  --seed          seeds python/numpy/torch/albumentations and the Trainer
  --train_prompt  'investigative' (SAFAID, notebook default) or 'category' (CatAID template, Train-13.ipynb)
  --stop_step     stop at this optimizer step of the 3-epoch cosine schedule (paper model = checkpoint-1600)
  ablation / baseline options (defaults reproduce the SAFAID runs exactly):
  --train_prompt vanilla   plain question without the investigative framing (Table 2 ablation)
  --aug_mode      fake_only (SAFAID) | uniform (same pipeline on real and fake) | none
  --schedule_steps fix the cosine schedule length in optimizer steps (3750 = SAFAID's 3 epochs x 1250), so
                  ablations with a different number of samples follow the identical LR trajectory
  --method qlora  4-bit QLoRA with the Train-13.ipynb adapter config (r=16, alpha=16, all layers, LR 2e-4, adamw_8bit)
  file logging    config.json, loss.csv, progress.json, trainer_state.json in the run folder
The training subset is the fixed, seeded manifest instead of os.listdir()[:100] (not reproducible).
"""
import os, sys, json, time, random, argparse, csv, platform, subprocess

# ---- paths (release) ----
# Defaults reproduce the layout of the paper runs (vast.ai, /workspace/safaid); override with env vars or CLI flags.
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKDIR = os.environ.get("SAFAID_WORKDIR", "/workspace/safaid")
DATA = os.environ.get("SAFAID_DATA", os.path.join(WORKDIR, "data"))
RUNS = os.environ.get("SAFAID_RUNS", os.path.join(WORKDIR, "runs"))
MANIFESTS = os.environ.get("SAFAID_MANIFESTS", os.path.join(REPO, "manifests"))

p = argparse.ArgumentParser()
p.add_argument("--run_name", required=True)
p.add_argument("--seed", type=int, required=True)
p.add_argument("--train_prompt", choices=["investigative", "category", "vanilla"], default="investigative")
p.add_argument("--aug_mode", choices=["fake_only", "uniform", "none"], default="fake_only")
p.add_argument("--schedule_steps", type=int, default=0, help="0 = num_train_epochs=3 as in the notebook")
p.add_argument("--method", choices=["full", "qlora"], default="full")
p.add_argument("--stop_step", type=int, default=1600)
p.add_argument("--data_dir", default=os.path.join(DATA, "progan_train_subset"))
p.add_argument("--manifest", default=os.path.join(MANIFESTS, "safaid_train_subset_v2_seed0.csv"))
p.add_argument("--out_root", default=RUNS)
args = p.parse_args()

RUN_DIR = os.path.join(args.out_root, args.run_name)
OUTPUT_DIR = os.path.join(RUN_DIR, "model")
os.makedirs(RUN_DIR, exist_ok=True)

random.seed(args.seed)
import numpy as np
np.random.seed(args.seed)

# ---- notebook cell 4 (unchanged) ----
MAX_SAMPLES_PER_CATEGORY = 100
MAX_SEQ_LENGTH = 2048
BATCH_SIZE = 1
GRADIENT_ACCUMULATION = 8
NUM_EPOCHS = 3
LEARNING_RATE = 5e-6
if args.method == "qlora":
    LEARNING_RATE = 2e-4  # Train-13.ipynb

# ---- notebook cell 3: categories, prompt, response (unchanged) ----
PROGAN_CATEGORIES = [
    "airplane", "bicycle", "bird", "boat", "bottle",
    "bus", "car", "cat", "chair", "cow",
    "diningtable", "dog", "horse", "motorbike", "person",
    "pottedplant", "sheep", "sofa", "train", "tvmonitor"
]


def create_ccp_prompt(category):
    if args.train_prompt == "category":
        # CatAID template, as in Train-13.ipynb
        return f"This is an image of a {category}. Is this image generated by AI, or is it a real image?"
    if args.train_prompt == "vanilla":
        return "Is this image generated by AI, or is it a real image?"
    return f"This is an image that is under investigation. Is this image generated by AI, or is it a real image?"


def create_response(label):
    """Create response based on label."""
    if label == "real":
        return "This is a real image."
    else:
        return "This is an AI-generated image."


def load_manifest_samples():
    samples = []
    with open(args.manifest) as f:
        for row in csv.DictReader(f):
            if row["split"] != "train":
                continue
            samples.append({
                "image_path": os.path.join(args.data_dir, row["name"]),
                "category": row["category"],
                "label": "real" if row["label"] == "0_real" else "fake",
            })
    random.shuffle(samples)
    print(f"Loaded {len(samples)} samples for train")
    return samples


train_samples = load_manifest_samples()
assert len(train_samples) == 4000, len(train_samples)
missing = [s["image_path"] for s in train_samples if not os.path.exists(s["image_path"])]
assert not missing, f"{len(missing)} training images missing, e.g. {missing[:3]}"

# ---- notebook cell 7: model (unchanged) ----
from unsloth import FastVisionModel
import torch
torch.manual_seed(args.seed)
torch.cuda.manual_seed_all(args.seed)
from trl import SFTTrainer, SFTConfig
from transformers import TrainerCallback

if args.method == "full":
    model, tokenizer = FastVisionModel.from_pretrained(
        "unsloth/Qwen3-VL-4B-Instruct",
        max_seq_length=MAX_SEQ_LENGTH,
        load_in_4bit=False,
        full_finetuning=True,
    )
else:  # Train-13.ipynb cell 9
    model, tokenizer = FastVisionModel.from_pretrained(
        "unsloth/Qwen3-VL-4B-Instruct",
        max_seq_length=MAX_SEQ_LENGTH,
        load_in_4bit=True,
    )
    model = FastVisionModel.get_peft_model(
        model,
        finetune_vision_layers=True,
        finetune_language_layers=True,
        finetune_attention_modules=True,
        finetune_mlp_modules=True,
        r=16,
        lora_alpha=16,
        lora_dropout=0,
        bias="none",
        random_state=args.seed,
    )

# ---- notebook cell 8: augmentation + conversion (unchanged, plus seed) ----
from PIL import Image
from tqdm import tqdm
import albumentations as A

aug_pipeline = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.ImageCompression(quality_lower=30, quality_upper=95, p=0.4),
    A.GaussianBlur(blur_limit=(3, 7), p=0.3),
    A.Downscale(scale_min=0.5, scale_max=0.9, p=0.2),
    A.RandomBrightnessContrast(brightness_limit=0.1, contrast_limit=0.1, p=0.2),
    A.GaussNoise(var_limit=(10, 30), p=0.1),
], seed=args.seed)


def convert_to_conversation(sample, num_augmented=0):
    category = sample["category"]
    label = sample["label"]
    image_path = sample["image_path"]

    image = Image.open(image_path).convert("RGB")
    prompt = create_ccp_prompt(category)
    response = create_response(label)

    results = []

    # Original
    results.append({
        "messages": [
            {"role": "user", "content": [{"type": "image", "image": image.copy()}, {"type": "text", "text": prompt}]},
            {"role": "assistant", "content": [{"type": "text", "text": response}]}
        ]
    })

    # Augmented copies
    if num_augmented > 0 and (label == "fake" or args.aug_mode == "uniform"):
        img_array = np.array(image)
        for _ in range(num_augmented):
            augmented = aug_pipeline(image=img_array)["image"]
            results.append({
                "messages": [
                    {"role": "user", "content": [{"type": "image", "image": Image.fromarray(augmented)}, {"type": "text", "text": prompt}]},
                    {"role": "assistant", "content": [{"type": "text", "text": response}]}
                ]
            })

    return results


converted_train = []
for s in tqdm(train_samples, desc="Converting train"):
    converted_train.extend(convert_to_conversation(s, num_augmented=0 if args.aug_mode == "none" else 3))
print(len(converted_train))
assert len(converted_train) == {"fake_only": 10000, "uniform": 16000, "none": 4000}[args.aug_mode]


# ---- logging (new) ----
def _v(mod):
    try:
        return __import__(mod).__version__
    except Exception:
        return None


config = {
    "run_name": args.run_name, "seed": args.seed, "train_prompt": args.train_prompt,
    "train_prompt_example": create_ccp_prompt("dog"), "stop_step": args.stop_step,
    "base_model": "unsloth/Qwen3-VL-4B-Instruct",
    "method": "full fine-tuning (bf16)" if args.method == "full" else "QLoRA 4-bit r=16 alpha=16 all layers (Train-13.ipynb)",
    "aug_mode": args.aug_mode, "schedule_steps": args.schedule_steps or "3 epochs",
    "num_train_samples": len(converted_train), "base_samples": len(train_samples),
    "manifest": os.path.basename(args.manifest), "num_augmented_per_image": 0 if args.aug_mode == "none" else 3,
    "lr": LEARNING_RATE, "epochs_schedule": NUM_EPOCHS, "batch_size": BATCH_SIZE,
    "grad_accum": GRADIENT_ACCUMULATION, "max_seq_length": MAX_SEQ_LENGTH,
    "optim": "adamw_torch" if args.method == "full" else "adamw_8bit", "lr_scheduler": "cosine", "warmup_ratio": 0.1, "bf16": True,
    "augmentation": "Train.ipynb pipeline unchanged (albumentations 1.x arg names)",
    "effective_augmentation_albumentations_2.0.8": {
        "HorizontalFlip": "p=0.5", "ImageCompression": "quality_range=(99,100) default, p=0.4",
        "GaussianBlur": "blur_limit=(3,7), p=0.3", "Downscale": "scale_range=(0.25,0.25) default, p=0.2",
        "RandomBrightnessContrast": "0.1/0.1, p=0.2", "GaussNoise": "std_range=(0.2,0.44) default, p=0.1"},
    "val_set": "omitted (notebook passed it but never evaluated: no eval_strategy)",
    "gpu": torch.cuda.get_device_name(0), "gpu_mem_gb": round(torch.cuda.get_device_properties(0).total_memory / 1e9, 1),
    "versions": {m: _v(m) for m in ["torch", "transformers", "trl", "peft", "accelerate", "unsloth", "unsloth_zoo", "albumentations", "numpy", "PIL"]},
    "python": platform.python_version(), "host": platform.node(),
    "started_utc": time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime()),
}
json.dump(config, open(os.path.join(RUN_DIR, "config.json"), "w"), indent=2)

T0 = time.time()
LOSS_CSV = os.path.join(RUN_DIR, "loss.csv")
with open(LOSS_CSV, "w") as f:
    f.write("step,epoch,loss,learning_rate,grad_norm,elapsed_s,max_mem_gb\n")


class FileLogger(TrainerCallback):
    def on_log(self, a, state, control, logs=None, **kw):
        logs = logs or {}
        el = time.time() - T0
        mem = torch.cuda.max_memory_allocated() / 1e9
        if "loss" in logs:
            with open(LOSS_CSV, "a") as f:
                f.write(f"{state.global_step},{logs.get('epoch', state.epoch)},{logs['loss']},"
                        f"{logs.get('learning_rate', '')},{logs.get('grad_norm', '')},{el:.1f},{mem:.2f}\n")
        s_per_step = el / max(state.global_step, 1)
        json.dump({"phase": "train", "step": state.global_step, "stop_step": args.stop_step,
                   "epoch": state.epoch, "last_loss": logs.get("loss"), "elapsed_min": round(el / 60, 1),
                   "s_per_step": round(s_per_step, 3),
                   "eta_min": round((args.stop_step - state.global_step) * s_per_step / 60, 1),
                   "max_mem_gb": round(mem, 2), "updated_utc": time.strftime("%H:%M:%S", time.gmtime())},
                  open(os.path.join(RUN_DIR, "progress.json"), "w"), indent=1)


class StopAtStep(TrainerCallback):
    def on_step_end(self, a, state, control, **kw):
        if state.global_step >= args.stop_step:
            control.should_save = True
            control.should_training_stop = True
        return control


# ---- notebook cell 10: trainer (unchanged except seed, save policy, callbacks) ----
from unsloth.trainer import UnslothVisionDataCollator
FastVisionModel.for_training(model)
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    data_collator=UnslothVisionDataCollator(model, tokenizer),
    train_dataset=converted_train,
    args=SFTConfig(
        output_dir=OUTPUT_DIR,
        num_train_epochs=NUM_EPOCHS,
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION,
        learning_rate=LEARNING_RATE,
        lr_scheduler_type="cosine",
        warmup_ratio=0.1,
        bf16=True,
        logging_steps=10,
        save_steps=args.stop_step,      # notebook: 100 (full checkpoints); only the evaluated step is kept
        save_only_model=True,
        save_total_limit=None,
        optim="adamw_torch" if args.method == "full" else "adamw_8bit",
        max_steps=args.schedule_steps if args.schedule_steps > 0 else -1,
        report_to="none",
        seed=args.seed,
        remove_unused_columns=False,
        dataset_text_field="",
        dataset_kwargs={"skip_prepare_dataset": True},
        max_seq_length=MAX_SEQ_LENGTH,
    ),
    callbacks=[FileLogger(), StopAtStep()],
)

print("\n" + "=" * 60)
print(json.dumps({k: config[k] for k in ["run_name", "seed", "train_prompt", "stop_step", "num_train_samples", "lr", "gpu"]}, indent=1))
print("=" * 60 + "\n")

trainer.train()

ckpt = os.path.join(OUTPUT_DIR, f"checkpoint-{args.stop_step}")
assert os.path.isdir(ckpt), f"expected {ckpt}"
try:
    tokenizer.save_pretrained(ckpt)
except Exception as e:
    print("processor save failed:", e)
import shutil
shutil.copy(os.path.join(ckpt, "trainer_state.json"), os.path.join(RUN_DIR, "trainer_state.json"))
eval_model = ckpt
if args.method == "qlora":  # merge the adapter into a 16-bit model for eval.py (as Train-13.ipynb did)
    eval_model = ckpt + "-merged16"
    model.save_pretrained_merged(eval_model, tokenizer, save_method="merged_16bit")
config.update({"finished_utc": time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime()),
               "train_minutes": round((time.time() - T0) / 60, 1),
               "peak_mem_gb": round(torch.cuda.max_memory_allocated() / 1e9, 2), "checkpoint": ckpt, "eval_model": eval_model})
json.dump(config, open(os.path.join(RUN_DIR, "config.json"), "w"), indent=2)
open(os.path.join(RUN_DIR, "TRAIN_DONE"), "w").write(eval_model + "\n")
print("TRAIN_DONE", ckpt)
