"""Fixed prompt list for the post-cutoff contamination test (200 prompts).

Groups: the 20 PASCAL VOC / ForenSynths ProGAN categories (6 prompts each = 120),
LSUN-style scenes (30), faces/portraits (25), landscapes/nature (25). All prompts ask for
ordinary photographs, because the real side is ordinary Wikimedia Commons photographs.
They name no real people, brands or text.

gen_fakes.py shuffles this list once with a fixed seed and cycles it, so image i uses
prompt order[i % 200] and seed base_seed + i. The (prompt, seed) pairs are the same for
every generator, which gives a paired design across generators.
Do not edit this list after images have been generated: PROMPTS_SHA256 is written into
each generator's run_info.json.
"""
import hashlib
import json

PROMPTS = [
    # ---- 20 VOC / ProGAN categories x 6 ----
    ("airplane", "A photo of a white passenger airplane taking off from a runway on an overcast afternoon, landing gear still down, wet tarmac"),
    ("airplane", "A small single-engine propeller plane parked on a grass airfield, late afternoon sun, a few trees in the background"),
    ("airplane", "View of a commercial jet wing through an airplane window above the clouds at sunrise"),
    ("airplane", "A vintage biplane on display in a museum hangar, people looking at it, fluorescent lighting"),
    ("airplane", "A cargo plane on an airport apron at night being loaded, orange floodlights, workers in reflective vests"),
    ("airplane", "Amateur photo of an airliner flying low over rooftops on its final approach, blue sky with thin clouds"),
    ("bicycle", "A red city bicycle leaning against a brick wall on a quiet street, morning light"),
    ("bicycle", "A mountain biker riding down a muddy forest trail, motion blur, shot from the side"),
    ("bicycle", "Several rental bicycles lined up at a docking station in a busy city square"),
    ("bicycle", "An old rusty bicycle with a wicker basket parked next to a wooden fence in the countryside"),
    ("bicycle", "A road cyclist in a race climbing a steep mountain road, spectators on the roadside"),
    ("bicycle", "A child learning to ride a small bicycle in a park while a parent runs alongside, autumn leaves"),
    ("bird", "A robin perched on a snowy branch, shallow depth of field, telephoto lens"),
    ("bird", "A flock of seagulls flying over a harbor with fishing boats, cloudy sky"),
    ("bird", "A great blue heron standing in shallow water at a lake shore at dawn"),
    ("bird", "Close-up of a pigeon walking on a city sidewalk, pedestrians blurred in the background"),
    ("bird", "A colorful parrot sitting on a branch in a tropical aviary, soft natural light"),
    ("bird", "Two ducks swimming on a pond in a city park, ripples on the water, afternoon light"),
    ("boat", "A small wooden fishing boat pulled up on a sandy beach at low tide"),
    ("boat", "A white sailboat with full sails on a choppy sea, bright sunny day"),
    ("boat", "Colorful rowing boats moored in a narrow canal between old houses"),
    ("boat", "A large ferry arriving at a pier on a foggy morning, passengers on the deck"),
    ("boat", "A kayaker paddling on a calm mountain lake, reflections of pine trees"),
    ("boat", "Motorboats docked in a marina at sunset, masts and ropes in the foreground"),
    ("bottle", "A glass bottle of olive oil on a kitchen counter next to tomatoes and garlic"),
    ("bottle", "Empty green glass bottles lined up on a windowsill with sunlight shining through them"),
    ("bottle", "A plastic water bottle lying on a hiking trail next to a backpack"),
    ("bottle", "Wine bottles stacked on wooden shelves in a dim cellar"),
    ("bottle", "A baby bottle with milk on a white table, soft window light"),
    ("bottle", "A row of unlabeled amber medicine bottles on a pharmacy shelf"),
    ("bus", "A red double-decker bus driving down a busy city street in the rain"),
    ("bus", "A yellow school bus parked in front of a brick school building in the morning"),
    ("bus", "Passengers boarding a city bus at a bus stop at dusk, street lights turning on"),
    ("bus", "An old retro tour bus parked at a mountain viewpoint, tourists taking photos"),
    ("bus", "Interior of a crowded commuter bus, people standing and holding the handrails"),
    ("bus", "An electric bus charging at a depot, overcast day, several buses in a row"),
    ("car", "A silver sedan parked on a suburban street lined with trees, midday"),
    ("car", "A classic car from the 1960s at an outdoor car show, people walking around"),
    ("car", "Traffic jam on a highway at sunset, red tail lights stretching into the distance"),
    ("car", "A muddy SUV driving on a dirt road through a forest"),
    ("car", "A small hatchback car covered in snow in a parking lot on a winter morning"),
    ("car", "The dashboard and steering wheel of a car photographed from the back seat, city street visible through the windshield"),
    ("cat", "A tabby cat sleeping curled up on a windowsill in the sun"),
    ("cat", "A black cat sitting on a garden wall looking at the camera"),
    ("cat", "A fluffy white cat playing with a toy mouse on a wooden floor"),
    ("cat", "A kitten peeking out of a cardboard box, indoor lighting"),
    ("cat", "An orange cat walking along a narrow alley between old buildings"),
    ("cat", "Two cats sitting on a sofa next to each other, evening lamp light"),
    ("chair", "A wooden chair next to a window in an empty room with white walls"),
    ("chair", "Rows of plastic chairs set up on a lawn for an outdoor wedding"),
    ("chair", "An office chair at a cluttered desk with papers and a coffee mug"),
    ("chair", "An old leather armchair in a library corner beside a floor lamp"),
    ("chair", "Folding chairs and a table on a camping site in the woods"),
    ("chair", "Colorful metal chairs outside a cafe on a cobblestone street"),
    ("cow", "A herd of cows grazing in a green pasture on a cloudy day"),
    ("cow", "A brown and white cow looking over a wooden fence, close-up"),
    ("cow", "Dairy cows standing in a barn during milking time"),
    ("cow", "A calf lying in the grass next to its mother in an alpine meadow"),
    ("cow", "Cattle walking along a dusty country road at sunset, a farmer behind them"),
    ("cow", "A black cow standing in the rain in a muddy field"),
    ("diningtable", "A dining table set for a family dinner with plates, glasses and a roast chicken"),
    ("diningtable", "A wooden kitchen table with breakfast: toast, coffee and a newspaper, morning light"),
    ("diningtable", "A long table at an outdoor summer party in a garden, string lights above"),
    ("diningtable", "A restaurant table for two with candles and wine glasses"),
    ("diningtable", "A messy table after a birthday party with leftover cake and paper cups"),
    ("diningtable", "A round table in a small apartment with a vase of flowers and a laptop"),
    ("dog", "A golden retriever running on a beach with a tennis ball in its mouth"),
    ("dog", "A small terrier sitting on a sofa looking at the camera"),
    ("dog", "A dog on a leash walking with its owner on a snowy sidewalk"),
    ("dog", "A sleepy old dog lying on a porch in the afternoon sun"),
    ("dog", "A puppy playing in autumn leaves in a backyard"),
    ("dog", "A sheepdog herding sheep in a hilly field"),
    ("horse", "A brown horse grazing in a meadow next to a wooden fence"),
    ("horse", "A rider jumping a horse over an obstacle at an equestrian competition"),
    ("horse", "Two horses standing in a snowy paddock, breath visible in the cold air"),
    ("horse", "A white horse running across a field at sunset"),
    ("horse", "A horse-drawn carriage on an old town street with tourists"),
    ("horse", "A foal standing close to its mother in a stable"),
    ("motorbike", "A motorcycle parked on the side of a mountain road with a view of the valley"),
    ("motorbike", "A scooter rider waiting at a traffic light in a busy Asian city"),
    ("motorbike", "A vintage motorbike in a garage workshop, tools on the wall"),
    ("motorbike", "A motocross rider jumping over a dirt hill, dust in the air"),
    ("motorbike", "Several motorcycles parked in a row outside a roadside cafe"),
    ("motorbike", "A delivery rider on a motorbike in the rain at night, neon reflections on the road"),
    ("person", "A man jogging in a park early in the morning, trees and a path behind him"),
    ("person", "A woman reading a book on a bench in a train station"),
    ("person", "A street musician playing guitar on a pedestrian street, people passing by"),
    ("person", "A farmer working in a rice field, wearing a straw hat"),
    ("person", "A group of friends hiking on a mountain trail, seen from behind"),
    ("person", "A chef preparing food in a busy restaurant kitchen"),
    ("pottedplant", "A potted monstera plant next to a sunny window in a living room"),
    ("pottedplant", "Small succulents in terracotta pots on a balcony railing"),
    ("pottedplant", "A row of potted herbs on a kitchen windowsill: basil, rosemary and mint"),
    ("pottedplant", "A large ficus tree in a pot in the corner of an office lobby"),
    ("pottedplant", "Flower pots with red geraniums outside a stone cottage"),
    ("pottedplant", "Rows of seedlings in plastic pots inside a greenhouse"),
    ("sheep", "A flock of sheep grazing on a green hillside with stone walls"),
    ("sheep", "A lamb standing in the grass next to its mother in spring"),
    ("sheep", "Sheep crossing a narrow country road, a car waiting behind them"),
    ("sheep", "A shepherd with his flock on a dry mountain slope"),
    ("sheep", "Close-up of a sheep's face with thick wool, looking at the camera"),
    ("sheep", "Sheep inside a wooden barn eating hay"),
    ("sofa", "A grey fabric sofa with cushions in a bright living room"),
    ("sofa", "An old leather sofa in a cozy study with bookshelves"),
    ("sofa", "A family sitting on a sofa watching television in the evening"),
    ("sofa", "A dog sleeping on a red sofa in a small apartment"),
    ("sofa", "An old sofa left outside on a sidewalk next to trash bins"),
    ("sofa", "A modern corner sofa in a showroom, soft studio lighting"),
    ("train", "A high-speed train passing through a green countryside"),
    ("train", "A steam locomotive at a heritage railway station, steam rising"),
    ("train", "Commuters waiting on a subway platform as a train arrives"),
    ("train", "A freight train crossing a bridge over a river in autumn"),
    ("train", "A tram on a city street in the evening, overhead wires"),
    ("train", "Inside a train carriage with passengers looking out of the windows at mountains"),
    ("tvmonitor", "A flat-screen television on a wooden stand in a living room, the screen turned off"),
    ("tvmonitor", "A computer monitor on an office desk showing a spreadsheet, keyboard and mouse in front"),
    ("tvmonitor", "An old CRT television on a shelf in a second-hand shop"),
    ("tvmonitor", "Two monitors on a desk in a dark room, glowing screens, a person working"),
    ("tvmonitor", "A wall of televisions in an electronics store"),
    ("tvmonitor", "A small TV in a hotel room on a dresser, a bed in the foreground"),
    # ---- LSUN-style scenes x 3 ----
    ("bedroom", "A bedroom with a double bed, white sheets and a bedside lamp, morning light through curtains"),
    ("bedroom", "A child's bedroom with bunk beds, toys on the floor and posters on the wall"),
    ("bedroom", "A hotel bedroom with a large bed, a desk and a window overlooking the city"),
    ("church", "The exterior of an old stone church with a bell tower, green lawn, blue sky"),
    ("church", "A small white village church on a hill, cloudy day"),
    ("church", "A large gothic cathedral facade photographed from a square, tourists in front"),
    ("kitchen", "A modern kitchen with white cabinets, a gas stove and a bowl of fruit on the counter"),
    ("kitchen", "A small rustic kitchen with wooden shelves, pots and pans hanging on the wall"),
    ("kitchen", "A kitchen after cooking, dirty dishes in the sink, evening light"),
    ("living_room", "A living room with a fireplace, an armchair and a rug, warm lamp light"),
    ("living_room", "A minimalist living room with large windows and a view of trees"),
    ("living_room", "A cluttered living room with toys, a sofa and a television"),
    ("tower", "A tall radio tower on a hill against a clear sky"),
    ("tower", "An old stone watchtower on a coastal cliff"),
    ("tower", "A modern glass skyscraper photographed from street level looking up"),
    ("bridge", "A suspension bridge over a wide river at dusk, city lights in the background"),
    ("bridge", "An old stone arch bridge over a small stream in a village"),
    ("bridge", "A wooden footbridge in a forest covered with fallen leaves"),
    ("classroom", "An empty classroom with rows of desks, a whiteboard and large windows"),
    ("classroom", "Students sitting in a lecture hall listening to a teacher"),
    ("classroom", "A primary school classroom with colorful drawings on the walls"),
    ("conference_room", "A conference room with a long table, chairs and a projector screen"),
    ("conference_room", "People in a business meeting around a table with laptops"),
    ("conference_room", "A small meeting room with glass walls in a modern office"),
    ("dining_room", "A formal dining room with a chandelier and a long wooden table"),
    ("dining_room", "A dining room in a farmhouse with mismatched chairs"),
    ("dining_room", "A dining room with a set table and a view of the garden"),
    ("restaurant", "A busy restaurant interior at dinner time with waiters and guests"),
    ("restaurant", "A small street food stall at night with customers sitting on stools"),
    ("restaurant", "An empty cafe in the morning with chairs on the tables"),
    # ---- faces / portraits (25) ----
    ("face", "Close-up portrait of an elderly man with a white beard and wrinkles, natural window light"),
    ("face", "Portrait of a young woman with curly hair smiling, outdoor, soft afternoon light"),
    ("face", "Headshot of a middle-aged man in a suit against a grey background"),
    ("face", "A teenage boy with freckles looking at the camera, overcast daylight"),
    ("face", "Portrait of an older woman with grey hair and glasses in her garden"),
    ("face", "A young man with a beard laughing, photographed on a city street"),
    ("face", "A little girl with braided hair holding a flower, park background"),
    ("face", "Close-up of a woman's face with light makeup, studio lighting"),
    ("face", "Portrait of a construction worker wearing a hard hat, sunny day"),
    ("face", "A man wearing a knitted hat in the snow, cold red cheeks"),
    ("face", "A smiling nurse in scrubs in a hospital corridor"),
    ("face", "Portrait of a fisherman on a boat, weathered face, sea in the background"),
    ("face", "A young woman with short dark hair in a coffee shop, looking out of the window"),
    ("face", "An old woman wearing a headscarf at a market stall"),
    ("face", "A student with glasses in a library, portrait, shallow depth of field"),
    ("face", "Portrait of a man with a mustache wearing a flat cap, black and white photo"),
    ("face", "A baby lying on a blanket looking up at the camera"),
    ("face", "Two friends taking a selfie together at a festival"),
    ("face", "A woman with red hair in a field of tall grass at golden hour"),
    ("face", "Portrait of a boy in a football jersey on a sports field"),
    ("face", "A man with tattoos on his arms sitting on steps outside a building"),
    ("face", "A grandmother and a grandchild smiling together in a kitchen"),
    ("face", "Close-up of a young man's face in the rain, water drops on his skin"),
    ("face", "Passport-style photo of a middle-aged woman against a white background"),
    ("face", "An athlete resting after a run, sweaty face, stadium in the background"),
    # ---- landscapes / nature (25) ----
    ("landscape", "Snow-capped mountains reflected in a still alpine lake at sunrise"),
    ("landscape", "Rolling green hills with farmland and a single tree, cloudy sky"),
    ("landscape", "A sandy beach with waves and palm trees, bright midday sun"),
    ("landscape", "A dense pine forest in the fog early in the morning"),
    ("landscape", "Red sand dunes in a desert under a clear blue sky"),
    ("landscape", "A waterfall in a rainforest surrounded by ferns and moss"),
    ("landscape", "A city skyline at night seen from across a river"),
    ("landscape", "A field of sunflowers in summer with a farmhouse in the distance"),
    ("landscape", "A rocky coastline with waves crashing, stormy sky"),
    ("landscape", "Autumn forest with orange and yellow leaves along a hiking path"),
    ("landscape", "A frozen lake with snow-covered trees on a winter day"),
    ("landscape", "Terraced rice fields on a hillside in the morning mist"),
    ("landscape", "A country road winding through vineyards in late summer"),
    ("landscape", "A volcanic landscape with black rocks and sparse vegetation"),
    ("landscape", "Lavender fields in rows under a warm evening sky"),
    ("landscape", "A small fishing village on the coast seen from a hill"),
    ("landscape", "A canyon with layered red rock walls and a river at the bottom"),
    ("landscape", "A meadow with wildflowers in the mountains, cows in the distance"),
    ("landscape", "A busy street market in an old town, stalls with fruit and vegetables"),
    ("landscape", "Suburban houses with front yards on a sunny afternoon"),
    ("landscape", "A glacier with blue ice and crevasses under a cloudy sky"),
    ("landscape", "An industrial harbor with cranes and containers at dusk"),
    ("landscape", "A lighthouse on a rocky point with the sea at sunset"),
    ("landscape", "A foggy river valley seen from a mountain top at dawn"),
    ("landscape", "Rain on a city street with umbrellas and reflections on the wet pavement"),
]

assert len(PROMPTS) == 200, len(PROMPTS)
assert len({p for _, p in PROMPTS}) == 200, "duplicate prompts"

PROMPTS_SHA256 = hashlib.sha256(json.dumps(PROMPTS, ensure_ascii=False).encode()).hexdigest()
